[versions]
constraintlayout-compose = "1.1.0"
sdk-minimal = "30"
sdk-target = "35"
activity-compose = "1.8.0"
kotlin = "2.0.0"
compose-bom = "2024.04.01"
foundation-layout-android = "1.6.6"
jetbrains-kotlin-jvm = "1.9.24"
junit = "4.13.2"
junit-version = "1.2.1"
espresso-core = "3.6.1"
material3 = "1.3.2"
junit-junit = "4.13.2"
androidx-junit = "1.3.0"
espresso-core-version = "3.5.1"
material = "1.10.0"
runtime = "1.9.5"

[libraries]
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.13.1" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.8.4" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.8.6" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.8.6" }
androidx-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version = "1.0.0" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.2" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version = "2.51.1" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version = "2.51.1" }
dagger-hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.2.0" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.12.0" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
okhttp-logger = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.11.0" }
retrofit-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version = "2.9.0" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.9.0" }

androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version = "1.2.1" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundation-layout-android" }
junit = { group = "junit", name = "junit", version.ref = "junit-junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core-version" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }

[plugins]
application-gradle-plugin = { id = "com.android.application", version = "8.9.1" }
library-gradle-plugin = { id = "com.android.library", version = "8.9.1" }
kotlin-android-gradle-plugin = { id = "org.jetbrains.kotlin.android", version = "2.0.0" }
kotlin-parcelize-gradle-plugin = { id = "org.jetbrains.kotlin.plugin.parcelize", version = "2.0.0" }
ksp-devtools-gradle-plugin = { id = "com.google.devtools.ksp", version = "2.0.0-1.0.22" }
dagger-hilt-gradle-plugin = { id = "com.google.dagger.hilt.android", version = "2.51.1" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin-jvm" }

[bundles]
androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-constraint-layout",
    "androidx-cardview",
    "androidx-fragment-ktx",
    "androidx-recyclerview",
]

networking = [
    "okhttp",
    "okhttp-logger",
    "retrofit",
    "retrofit-converter-gson",
    "retrofit-converter-scalars",
]
